# -*- coding: utf-8 -*-
"""nisanth internal

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/150KNlhPZfhxnO6pnvb9xZMroH5IVO8Up
"""

a=("I am signing up for Replit 100 days of Python challenge! I will make sure to spend some time every day coding along, for a minimum of 10 minutes a day. I'll be using Replit, an amazing online IDE so I can do this from my phone wherever I happend to be. No excuses for not coding from the middle of a field!")

print(a)

my_dict={"spyware":"Spyware is malicious software that enters a user's computer, gathers data from the device and user, and sends it to third parties without their consent. A commonly accepted spyware definition is a strand of malware designed to access and damage a device without the user's consent."}
print(my_dict)

a=12300
gst=12300*18/100
print(gst)
print(a+gst)

print("\t\t\tcalculating EB bill")
type=int(input("\n select the residntial palce:\n\n1.household\n2.commercial\n"))
if(type ==1):
  def house():
    print("EB Bill for your House:")
    
    unit=int(input("enter the units:"))
    if(unit<=100):
        ui=unit*0.50
    elif unit>=101 and unit<200:
         ui=unit*0.75
    elif unit<201 and unit<300:
         ui=unit*1.20
    elif unit>300:
         ui=unit*1.50    
    
    print("total charges:",ui)
  house()  
if(type ==2):
     def com():
      print("EB Bill for your Commercial palce:")
   
     unit=int(input("enter the units:"))
     if (unit<=100):
        ui=unit*0.50
     elif unit>=101 and unit<200:
         ui=unit*0.75
     elif unit<201 and unit<300:
         ui=unit*1.20
     elif unit>300:
         ui=unit*1.50    
    
     print("total charges:",ui)
     com()

import pandas as pd
student_data=pd.DataFrame(
    {"Student_Name": ["nisanth", "kalai", "nambi", "veruman", "badboy", "jeeva", "haris", "santhosh", "kanna", "vijay"],
     "Age": [20,20,20,20,20,20,20,20,20,20],
     "DOB(year)": [2001,1999,2001,1998,2001,2001,2001,2004,2001,2003],
     "Weight(kg)" : [60,62,75,80,49,55,83,66,73,72],
     "Height(cm)" : [150,120,135,177,156,188,199,154,177,133]}
)

student_data["BMI"]=student_data["Weight(kg)"]/student_data["Height(cm)"]*student_data["Height(cm)"]

student_data["Status"]=student_data["BMI"].apply(lambda x: "Normal" if x>50 and x<80 else "Underweight")
# print(student_data)


student_data.to_csv("student_data.csv")
student_data=pd.read_csv("/content/student_data.csv")
student_data